---

name: automated-tests

on:
    schedule:
        - cron: "0 0 * * *"
    push:
        branches-ignore:
            - main

jobs:
    automated-tests:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
          - name: Install python
            uses: actions/setup-python@v5
            with:
              python-version: 3.12
          - name: Install dependencies
            run: pip3 install -r requirements.txt
          - name: start stack
            run: dsp-tools start-stack --no-prune
          - name: run tests
            run: pytest test


